#!/bin/bash

echo "$1 $2" | awk -i awklib/colorfunks.awk '
{
  # addcolor("#FFFFFF")
  # addcolor("#000000")
  # addcolor($1)

  # if (ac[$1]["dark"]) {print $1 " is dark"}
  # else {print $1 " is light"}
  print less($1,$2)
  # if (ac[$1]["HEX"]["R"] !~ /./) {
  #   print "dd"
  #   addcolor($1)
  # }
}
'
